name: PR pipeline
on:
  pull_request:
    branches: master
    types: [closed]

jobs:
  get-bump:
    if: github.event.pull_request.merged == true
    name: Get version bump
    runs-on: ubuntu-latest
    outputs:
      bump: ${{ steps.get-version-bump.outputs.bump }}
    steps:
      -
        name: Get version bump
        id: get-version-bump
        uses: husarion-ci/action-get-version-bump@v0.3.0

  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    needs: get-bump
    if: needs.get-bump.outputs.bump != 'none' && github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ needs.get-bump.outputs.bump }}

      - name: Create tag
        run: git tag ${{ steps.bump-semver.outputs.new_version }}
      
      - name: Publish tags
        run: git push --tags